### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [FakeSmileUX/SpotifyChecker#1]
![image](https://user-images.githubusercontent.com/47924522/90216852-ac7b0900-ddcd-11ea-92e6-88dcffe09e25.png)
I got this error when I try to run the script[](url)

**Comment by FakeSmileUX** [comment]
> ![image](https://user-images.githubusercontent.com/47924522/90216852-ac7b0900-ddcd-11ea-92e6-88dcffe09e25.png)
> I got this error when I try to run the script

+I fixed error now you can use it with "python2 SpotifyChecker.py".
+Sorry for late answer and fix...
+Dont forget install requests.
